config/routes.rb
Rails.application.routes.draw do

  get 'articles/new'
  get 'articles/show'
  get 'articles/edit'
  resources :articles

  root 'articles#index'
 
  get 'tags/:tag', to: 'articles#index', as: :tag, :constraints  => { :tag => /[^\/]+/ }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :taggings
  has_many :tags, through: :taggings

  def self.tagged_with(name)
   Tag.find_by!(name: name).articles
 end

 def self.tag_counts
   Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
 end

 def tag_list
   tags.map(&:name).join(', ')
 end

 def tag_list=(names)
   self.tags = names.split(',').map do |n|
     Tag.where(name: n.strip).first_or_create!
   end
 end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = if params[:tag]
     Article.tagged_with(params[:tag])
   else
     Article.all
   end
  end

  def new
    @article = Article.new
  end

  def show
     @article = Article.find(params[:id])
  end
  def create
      @article = Article.new(article_params)
      if @article.save
        redirect_to @article, notice: 'Created article.'
      else
        render :new
      end
    end
  def edit
        @article = Article.find(params[:id])
  end
  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(article_params)
      redirect_to @article, notice: 'Updated article.'
    else
      render :edit
    end
  end
  private

def article_params
  params.require(:article).permit(:name, :published_on, :content, :tag_list)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h3>Edit article</h3>
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="all_articles">
  <div class="container">
    <div class="row">
      <div class="col-md-12">


<h4>Articles</h4>

<div id="tag_cloud">
  <% tag_cloud Article.tag_counts, %w[s m l] do |tag, css_class| %>
    <small>
      <i>
        <em>
      <%= link_to tag.name, tag_path(tag.name), class: css_class %>
     </em>
    </i>
  </small>
  <% end %>
</div>

<div id="articles">
  <% @articles.each do |article| %>
  <div class="card">
    <div class="card-body">
    <h4><%= link_to article.name, article %></h4>
    <%= simple_format article.content %>
    <p class="badge badge-warning">
      Tags: <%= raw article.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ')   %>
    </p>
    <p><%= link_to "Edit Article", edit_article_path(article) %></p>
  </div>
</div>
  <% end %>
</div>

<p><%= link_to "New Article", new_article_path %></p>
</div>
</div>
</div>
</div>

app/views/articles/new.html.erb
<h3>Create new article</h3>
<%= render 'form' %>

app/views/articles/show.html.erb
<h3><%= @article.name %></h3>
<p><%= @article.content %> </p>
<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tug</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://bootswatch.com/4/lux/bootstrap.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>